### ISSUE TITLE
Layout issue on click

### ISSUE THREAD

**Issue by dkarv** [JonasDoebertin/ha-today-card#40]
Thanks for the new interaction feature!
I noticed a layout issue:

![Image](https://github.com/user-attachments/assets/c524d4f9-6a82-44b0-955c-315cf76943ed)

I did a hard browser refresh without success.
Tried with latest Chrome and Firefox

**Comment by JonasDoebertin** [comment]
Thanks for letting me know. Did you set a fixed height for the card in the visual editor?

**Comment by dkarv** [comment]
It happens in both cases for me.

**Comment by dkarv** [comment]
It only happens when I add a tap_action. But without clicking. Without the tap_action, it looks normal.

Here is a screenshot of the layout in Firefox, that shows where the negative 8px come from:
![Image](https://github.com/user-attachments/assets/0daaf936-4c0f-4f1c-a339-d340efb99d6f)

I just recreated a minimal fresh dashboard to make sure no other cards are influencing it, with this yaml I can also reproduce it:
```
views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: custom:today-card
            advance: 0
            time_format: HH:mm
            show_all_day_events: true
            show_past_events: false
            tap_action:
              action: navigate
              navigation_path: /calendar
            entities:
              - entity: calendar.XXX
                color: ''

```
