### ISSUE TITLE
Card is empty

### ISSUE THREAD

**Issue by milandzuris** [JonasDoebertin/ha-today-card#41]
Hi, I dont see anything in the card its not working, why?

![Image](https://github.com/user-attachments/assets/ccaaabb5-6748-45cd-b047-8062ed616104)

![Image](https://github.com/user-attachments/assets/1d1c0051-b1be-4c91-a8e6-18b7bdc851f5)

```
type: custom:today-card
title: Today's Schedule
advance: 150
time_format: H:mm
show_all_day_events: true
show_past_events: false
entities:
  - entity: calendar.milan_dzuris
    color: ""
  - entity: calendar.meniny_narodeniny
    color: purple
  - entity: calendar.slovakia_holidays
    color: orange
  - entity: calendar.ufc
    color: red
  - entity: calendar.home_assistant_devs
    color: light-blue
  - entity: calendar.garbage_collection
    color: green
```
